# Generated by Django 4.0.2 on 2022-02-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialreminder', '0004_alter_person_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
